# Generated by Django 2.0.1 on 2019-04-28 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articlemodel',
            table='book',
        ),
    ]
