# Generated by Django 2.0.1 on 2019-04-28 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Article')),
                ('origin_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Comment')),
            ],
        ),
    ]
