# Generated by Django 2.0.1 on 2019-04-28 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='frontuser',
            table='front_user',
        ),
    ]
